name: Deploy Zola Blog to GitHub Pages

on:
  push:
    branches: [main]
    paths:
      - "nix-blog/**"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Blog Repository
        uses: actions/checkout@v4
        with:
          path: nix-blog

      - name: Install Zola
        run: |
          ZOLA_VERSION="0.20.0"
          wget https://github.com/getzola/zola/releases/download/v${ZOLA_VERSION}/zola-v${ZOLA_VERSION}-x86_64-unknown-linux-gnu.tar.gz
          tar -xzf zola-v${ZOLA_VERSION}-x86_64-unknown-linux-gnu.tar.gz
          mv zola /usr/local/bin/
          zola --version

      - name: Build Zola Site
        working-directory: nix-blog
        run: zola build

      - name: Deploy to GitHub Pages
        run: |
          # Use the correct repository name here
          REPO="saylesss88/saylesss88.github.io"
          #  Important: Use a PAT, and ensure the secret is named correctly
          TOKEN="${{ secrets.GH_PAGES_TOKEN }}"
          #  The directory where Zola output is located
          PUBLISH_DIR="nix-blog/public"

          #  Initialize a fresh git repo in the target directory
          TARGET_BRANCH="gh-pages"
          git init
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          #  Checkout the target branch if it exists, or create an orphan branch if it does not
          git fetch origin $TARGET_BRANCH --depth=1 || true
          git checkout $TARGET_BRANCH || git checkout --orphan $TARGET_BRANCH

          #  Clean the target directory
          rm -rf ./*

          #  Copy the Zola output to the target directory
          cp -r $PUBLISH_DIR/* .

          #  Add, commit, and push the changes
          git add -A
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Deploy Zola site to $TARGET_BRANCH"
            #  Use the PAT for authentication in the push URL
            git push "https://x-access-token:$TOKEN@github.com/$REPO" $TARGET_BRANCH -f
          fi
