---
# name: Build and deploy Zola to separate GitHub Pages repo

on:
  push:
    branches: [main]
    # paths:
    #   - "nix-blog/**"
# workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout blog repo
        uses: actions/checkout@v4
        with:
          path: nix-blog

      - name: Install Zola
        run: |
          ZOLA_VERSION="0.20.0"
          wget https://github.com/getzola/zola/releases/download/v${ZOLA_VERSION}/zola-v${ZOLA_VERSION}-x86_64-unknown-linux-gnu.tar.gz
          tar -xzf zola-v${ZOLA_VERSION}-x86_64-unknown-linux-gnu.tar.gz
          sudo mv zola /usr/local/bin/
          zola --version

      - name: Build Zola site
        working-directory: nix-blog
        run: zola build

      - name: Configure Git
        run: |
          git config --global user.name "saylesss88"
          git config --global user.email "saylesss88@proton.me"

      - name: Deploy to separate GitHub Pages repo
        env:
          GH_PAGES_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
        run: |
          REPO="saylesss88/saylesss88.github.io"
          TARGET_BRANCH="main"
          PUBLISH_DIR="nix-blog/public"

          # Clone the GitHub Pages repo
          git clone --depth 1 --branch $TARGET_BRANCH https://x-access-token:${GH_PAGES_TOKEN}@github.com/${REPO}.git gh-pages
          # git clone --depth 1 --branch $TARGET_BRANCH
          #  https://x-access-token:${GH_PAGES_TOKEN}@github.com/$REPO.git gh-pages

          cd gh-pages

          # Clean existing files
          git rm -rf .

          # Copy new site files
          cp -r ../$PUBLISH_DIR/* .

          # Commit and push if there are changes
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Deploy Zola site"
            git push origin $TARGET_BRANCH
          fi
