name: Deploy Zola Blog to GitHub Pages

on:
  push:
    branches: [main]
    paths:
      - "nix-blog/**"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Blog Repository
        uses: actions/checkout@v4
        with:
          path: nix-blog

      - name: Install Zola
        run: |
          ZOLA_VERSION="0.20.0"
          wget https://github.com/getzola/zola/releases/download/v${ZOLA_VERSION}/zola-v${ZOLA_VERSION}-x86_64-unknown-linux-gnu.tar.gz
          tar -xzf zola-v${ZOLA_VERSION}-x86_64-unknown-linux-gnu.tar.gz
          mv zola /usr/local/bin/
          zola --version

      - name: Build Zola Site
        working-directory: nix-blog
        run: zola build

      - name: Deploy to GitHub Pages
        run: |
          REPO="saylesss88/saylesss88.github.io"
          TOKEN="${{ secrets.GH_PAGES_TOKEN }}"
          PUBLISH_DIR="nix-blog/public"
          TARGET_BRANCH="gh-pages"

          # Initialize a fresh git repo
          cd nix-blog # Move out of the nix-blog directory
          git init

          # Configure git
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          # Checkout the target branch (or create if it doesn't exist)
          # git fetch origin $TARGET_BRANCH --depth=1 || true
          git fetch --all
          git branch --list $TARGET_BRANCH
          git checkout $TARGET_BRANCH || git checkout --orphan $TARGET_BRANCH

          # Clean the target directory
          # rm -rf ./*
          find . -not -name '.git' -exec rm -rf {} +


          # Copy the Zola output
          cp -r $PUBLISH_DIR/* .

          # Add, commit, and push
          git add -A
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Deploy Zola site to $TARGET_BRANCH"
            git remote add origin "https://x-access-token:$TOKEN@github.com/$REPO"
            git push origin $TARGET_BRANCH -f
          fi
